[package]
name = "tuto"
version = "0.1"
lean_version = "geektype/lean-apple:stable"
path = "src/solutions"

[dependencies]
mathlib = {git = "https://github.com/geektype/mathlib", rev = "d4f69d96f3532729da8ebb763f4bc26fcf640f06"}
